name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # allows you to trigger manually

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install  -r requirements.txt

      - name: Build site
        run: |
         cd site
         nikola build
         nikola check

      - name: Deploy to GitHub pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add site/output && git commit -m "[ci skip] Nikola auto deploy."
          git --no-pager log --oneline
