name: Register repository
on:
  issues:
    types:
      - opened

jobs:
  register-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Checkout clean xdevbot Branch
        run: |
          git checkout --orphan xdevbot
          git rm --cached -r .

      - name: Register new repository
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python -m pip install requests ruamel.yaml aiohttp
          python .github/workflows/register_repositories.py

      - name: Commit up-to-date config file
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add xdevbot.yaml && git commit -m "[skip ci] Update configuration file."

      - name: Push commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: xdevbot
          force: true

      - name: Send a reply message to the issue
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs')
            const logs = fs.readFileSync('hooks_log.md', 'utf8')
            const issue_reply = "The following changes were made:\n\n" + `${logs}`+ "\n\n***Check the [xdevbot branch](https://github.com/NCAR/xdev/blob/xdevbot/xdevbot.yaml) for latest configuration file changes.***"
            // Send a reply message to the issue
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issue_reply
            })
